[project]
name = "transformers"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Keith Dao", email = "keith.dao.248@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "datasets>=5.0.1",
    "torch>=2.13.0",
]

[project.scripts]
transformers = "transformers:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "ruff>=0.16.4",
]

[tool.ruff]
line-length = 120
indent-width = 4

[tool.ruff.lint]
select = ["ALL"]
extend-ignore = [
    # No need for copyright in source code.
    "CPY001",
]

[tool.ruff.lint.per-file-ignores]
"tests/**/*.py" = [
    # No need for __init__.py in tests.
    "INP001",
    # Pytest relies on asserts for testing.
    "S101",
    # Argument count is not important for unit tests.
    "PLR0913",
    # Positional argument count is not important for unit tests.
    "PLR0917",
    # Positional boolean arguments are fine for unit tests.
    "FBT001",
]

[tool.ruff.lint.isort]
force-sort-within-sections = true

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
docstring-code-line-length = "dynamic"
